# Which tracks to generate
TRACKS := e23c16 e23g17 e23c18 e23e19 e23a22
TRACKS_345G := e23d15

# Revision of correlation run, e.g., v1a, gold253, gold261, gold262
#REV  := v1
REV := FRINGE

# Release version, e.g., 1
REL  := 0

# Name of site; used for ./filelists_<SITE>/
SITE := mpifr

# Top-level directory for Correlator output, any experiment
EXPROOT := /Exps/

